require([
  'spec/aeris/maps/gmaps/route/waypoint',
  'spec/aeris/maps/gmaps/route/route',
  'spec/aeris/maps/gmaps/route/routebuilder',
  'spec/aeris/maps/gmaps/route/routerenderer',
  'spec/aeris/maps/gmaps/route/commands/abstractroutecommand',
  'spec/aeris/maps/gmaps/route/commands/addwaypointcommand',
  'spec/aeris/maps/gmaps/route/commands/removewaypointcommand',
  'spec/aeris/maps/gmaps/route/commands/resetroutecommand',
  'spec/aeris/maps/gmaps/route/directions/abstractdirectionsservice',
  'spec/aeris/maps/gmaps/route/directions/googledirectionsservice'
]);
