require([
  'spec/aeris/maps/gmaps/route/waypoint',
  'spec/aeris/maps/gmaps/route/route',
  'spec/aeris/maps/gmaps/route/routebuilder',
  'spec/aeris/maps/gmaps/route/routerenderer',
  'spec/aeris/maps/gmaps/route/commands/addwaypointcommand',
  'spec/aeris/maps/gmaps/route/commands/removewaypointcommand',
  'spec/aeris/maps/gmaps/route/commands/clearroutecommand'
]);
