define(function() {
  /**
   * Helper for validating an object.
   *
   * @class ValidatorInterface
   * @namespace aeris.helpers.validator
   * @interface
   *
   * @param {Object} obj Object to validate.
   */
  var ValidatorInterface = function(obj) {};

  /**
   * @return {Boolean}
   * @method isValid
   */
  ValidatorInterface.prototype.isValid = function() {};

  /**
   * @return {Error} The error generated by the last call to isValid.
   * @method getLastError
   */
  ValidatorInterface.prototype.getLastError = function() {};


  return ValidatorInterface;
});
