/**
 * Defines a package of map layers.
 */
require([
  'base/layers/aerisadvisories',
  'base/layers/aerisadvisorieskml',
  'base/layers/aerischlorophyll',
  'base/layers/aerisconvectivehazards',
  'base/layers/aerisdewpoints',
  'base/layers/aerisheatindex',
  'base/layers/aerishumidity',
  'base/layers/aerisradar',
  'base/layers/aerissatellite',
  'base/layers/aerissatelliteglobal',
  'base/layers/aerissatellitevisible',
  'base/layers/aerisseasurfacetemps',
  'base/layers/aerissnowdepth',
  'base/layers/aeristemps',
  'base/layers/aeriswindchill',
  'base/layers/aeriswinds',
  'base/layers/googlehybrid',
  'base/layers/googleroadmap',
  'base/layers/googlesatellite',
  'base/layers/googleterrain',
  'base/layers/osm'
]);
