define(function() {
  /**
   * Helper for validating an object.
   *
   * @class aeris.helpers.validator.ValidatorInterface
   * @interface
   *
   * @param {Object} obj Object to validate.
   */
  var ValidatorInterface = function(obj) {};

  /** @return {Boolean} */
  ValidatorInterface.prototype.isValid = function() {};

  /**
   * @return {Error} The error generated by the last call to isValid.
   */
  ValidatorInterface.prototype.getLastError = function() {};


  return ValidatorInterface;
});